### ISSUE TITLE
Failed to activate the heroku package

### ISSUE THREAD

**Issue by ricardodantas** [jclem/heroku-atom#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [heroku](https://github.com/jclem/heroku-atom) package, v0.0.2

### Stack Trace

Failed to activate the heroku package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/ricardodantas/.atom/packages/heroku/lib/heroku.coffee:11:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:625:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
angularjs, v0.3.3
atom-autocomplete-php, v0.18.1
atom-jade, v0.3.0
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-ionic-framework, v0.2.1
autocomplete-modules, v1.3.1
autocomplete-sass, v0.1.0
cdnjs, v1.5.0
coffee-compile, v0.19.2
color-picker, v2.0.13
compass, v0.9.1
css-color-underline, v1.0.1
docblockr, v0.7.3
documentation-renderer, v0.2.1
editorconfig, v1.2.2
emmet, v2.3.14
express-complete, v0.2.0
file-icons, v1.6.11
git-log, v0.4.1
grunt-runner, v0.11.0
heroku, v0.0.2
html-entities, v0.4.0
javascript-snippets, v1.0.0
language-blade, v0.16.0
language-dustjs, v0.2.0
language-mustache, v0.13.0
laravel, v0.7.0
linter, v1.10.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-jade, v0.3.2
linter-scss-lint, v2.4.0
markdown-preview-plus, vundefined
node-debugger, v1.1.9
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
rest-client, v0.5.0
ssh-config, v0.10.1
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
terminal-status, v1.6.8
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by xtfer** [comment]
I'm still seeing this. What was the resolution?

**Comment by BenjaminHCCarr** [comment]
what was the solution? I am still getting this error.

I have a feeling it has to do with a `$PATH` problem to my heroku; but a known or documented solution would help a lot of us!
